import os
import sys
import json
import io
import asyncio
import sqlite3
import logging
from contextlib import asynccontextmanager
from fastapi import FastAPI
from aiogram import Bot, Dispatcher, types
from aiogram.filters import CommandStart
from aiogram.types import BufferedInputFile
from google import genai
from google.genai import types as genai_types

from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

# Setup Logging Metrics
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

if not TELEGRAM_TOKEN or not GEMINI_API_KEY:
    logging.critical("Deployment failed: Environment variables are missing!")
    sys.exit(1)

bot = Bot(token=TELEGRAM_TOKEN)
dp = Dispatcher()
ai_client = genai.Client(api_key=GEMINI_API_KEY)
DB_FILE = "easy_trip.db"

active_background_tasks = set()

# =====================================================================
# CORE ENGINE DATABASE LOGIC
# =====================================================================
def init_db():
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    cursor.execute('CREATE TABLE IF NOT EXISTS chat_history (user_id INTEGER, role TEXT, content TEXT)')
    conn.commit()
    conn.close()

def get_history(user_id: int):
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    cursor.execute("SELECT role, content FROM chat_history WHERE user_id = ?", (user_id,))
    rows = cursor.fetchall()
    conn.close()
    return [{"role": r, "parts": [c]} for r, c in rows]

def save_message(user_id: int, role: str, content: str):
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    cursor.execute("INSERT INTO chat_history (user_id, role, content) VALUES (?, ?, ?)", (user_id, role, content))
    conn.commit()
    conn.close()

# =====================================================================
# DYNAMIC PDF GENERATOR SERVICE
# =====================================================================
def create_itinerary_pdf(chat_history: list) -> io.BytesIO:
    pdf_buffer = io.BytesIO()
    doc = SimpleDocTemplate(pdf_buffer, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    story = []
    
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('TitleStyle', parent=styles['Heading1'], fontSize=24, spaceAfter=20)
    body_style = ParagraphStyle('BodyStyle', parent=styles['Normal'], fontSize=12, leading=16, spaceAfter=10)
    
    story.append(Paragraph("✈️ EasyTrip — Your Custom Handmap Plan", title_style))
    story.append(Spacer(1, 15))
    story.append(Paragraph("Here is the verified scope generated by your AI travel companion:", styles['Heading2']))
    story.append(Spacer(1, 10))
    
    for turn in chat_history:
        if turn['role'] == 'model' and "Final Plan Review" in turn['parts'][0]:
            clean_text = turn['parts'][0].replace("[TRIGGER_PDF]", "").replace("**", "")
            for line in clean_text.split('\n'):
                if line.strip():
                    story.append(Paragraph(line, body_style))
            break
    else:
        story.append(Paragraph("Custom trip data finalized successfully. Secure packing and clear skies ahead!", body_style))
        
    doc.build(story)
    pdf_buffer.seek(0)
    return pdf_buffer

# =====================================================================
# SOLIDIFIED MULTI-STAGE SYSTEM INSTRUCTIONS
# =====================================================================
SYSTEM_INSTRUCTION = """
You are an empathetic, natural, and efficient travel intake assistant for EasyTrip agency.

STAGE 1: GATHERING INFORMATION
Ask 1-2 short questions at a time to gather exactly these 5 elements:
1. Destination
2. Budget boundaries
3. Duration of stay
4. Vibe or specific interests
5. Dietary preferences or restrictions (accept answers like "none", "no restrictions", or "no")

STAGE 2: PRESENTING THE SUMMARY
The absolute second you have collected all 5 pieces of information, do not ask more follow up questions. Immediately present a clean text-based review summary titled exactly: "✨ **Final Plan Review**".
List out all 5 gathered details cleanly using bullet points. Conclude the message by asking: "Do you want to make any changes? If it looks good, let me know and I will build your handmap plan PDF file!"

STAGE 3: THE PDF GENERATION TRIGGER
ONLY after you have explicitly displayed the "✨ **Final Plan Review**" text block in a previous turn, if the user confirms everything looks good (e.g., says "yes", "looks great", "no changes", "finalize"): Output the exact string "[TRIGGER_PDF]" along with a friendly closing sign-off. Do not output raw python or code snippets.
"""

# =====================================================================
# TELEGRAM DISPATCH HANDLERS
# =====================================================================
@dp.message(CommandStart())
async def cmd_start(message: types.Message):
    user_id = message.from_user.id
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    cursor.execute("DELETE FROM chat_history WHERE user_id = ?", (user_id,))
    conn.commit()
    conn.close()
    
    welcome = "👋 Welcome to EasyTrip! I'm your AI partner. Where are we traveling next?"
    # FIX: We do NOT save the welcome message to chat_history anymore.
    # This guarantees the payload sequence sent to Gemini strictly starts with a 'user' turn.
    await message.answer(welcome)

@dp.message()
async def handle_chat_turn(message: types.Message):
    user_id = message.from_user.id
    if not message.text:
        return

    save_message(user_id, "user", message.text)
    history_rows = get_history(user_id)
    
    contents_payload = []
    for row in history_rows:
        contents_payload.append(
            genai_types.Content(role=row["role"], parts=[genai_types.Part.from_text(text=row["parts"][0])])
        )

    try:
        response = await ai_client.aio.models.generate_content(
            model="gemini-2.0-flash",
            contents=contents_payload,
            config=genai_types.GenerateContentConfig(
                system_instruction=SYSTEM_INSTRUCTION,
                max_output_tokens=700,
                temperature=0.3
            )
        )
        
        ai_response_text = response.text if response.text else ""

        if "[TRIGGER_PDF]" in ai_response_text:
            clean_reply = ai_response_text.replace("[TRIGGER_PDF]", "").strip()
            if clean_reply:
                await message.answer(clean_reply)
            
            await message.answer("⚙️ *Compiling your Handmap PDF Plan... Please wait a brief moment.*", parse_mode="Markdown")
            
            pdf_data = create_itinerary_pdf(history_rows)
            input_file = BufferedInputFile(pdf_data.read(), filename="EasyTrip_Itinerary.pdf")
            
            await message.answer_document(document=input_file, caption="✈️ Ready! Here is your official EasyTrip travel plan document. Have an amazing trip!")
            
            # Flush history clean for their next session
            conn = sqlite3.connect(DB_FILE)
            cursor = conn.cursor()
            cursor.execute("DELETE FROM chat_history WHERE user_id = ?", (user_id,))
            conn.commit()
            conn.close()
        else:
            if ai_response_text:
                save_message(user_id, "model", ai_response_text)
                await message.answer(ai_response_text)
            else:
                # Upgraded fallback warning for clearer diagnostics
                logging.warning(f"Empty text token generated for user: {user_id}")
                await message.answer("Let's make sure I have that down correctly. Could you repeat your last response?")

    except Exception as e:
        logging.error(f"Engine Exception: {e}")
        await message.answer(f"❌ Debug Error: {str(e)}")

# =====================================================================
# LIFECYCLE MANAGEMENT & WEB SYSTEM
# =====================================================================
async def run_bot_resiliently():
    while True:
        try:
            logging.info("Launching aiogram polling engine...")
            await dp.start_polling(bot, handle_signals=False, polling_timeout=30)
        except asyncio.CancelledError:
            break
        except Exception as proxy_error:
            logging.exception("CRITICAL Polling loop failure!")
            await asyncio.sleep(5)

@asynccontextmanager
async def lifespan(fastapi_app: FastAPI):
    init_db()
    supervisor_task = asyncio.create_task(run_bot_resiliently())
    active_background_tasks.add(supervisor_task)
    supervisor_task.add_done_callback(active_background_tasks.discard)
    yield
    await dp.stop_polling()
    supervisor_task.cancel()

app = FastAPI(lifespan=lifespan)

@app.get("/")
def health_check():
    return {"status": "EasyTrip Core Engine is online 24/7"}
